version: "2"
linters:
  default: all
  disable:
    - depguard
    - nlreturn
    - noinlineerr
    - revive
    - wsl
    - wsl_v5
  settings:
    exhaustruct:
      exclude:
        - '.*/components\.HTML5Props'
    funcorder:
      alphaabetical: true
    ireturn:
      allow:
        - gomponents.Node
        - http.Handler
    varnamelen:
      ignore-decls:
        - w http.ResponseWriter
  exclusions:
    warn-unused: true
    generated: lax
    #presets:
      #- comments
      #- common-false-positives
      #- legacy
      #- std-error-handling
formatters:
  enable:
    - gofumpt
    - golines
  settings:
    gofumpt:
      extra-rules: true
  exclusions:
    warn-unused: true
    generated: lax
