name: Publish Docker
on: [push]
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@master
        - name: Publish to Registry
          uses: elgohr/Publish-Docker-Github-Actions@3.03
          with:
              name: nusak/netmaker
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}
              default_branch: arm_docker
              platforms: linux/amd64, linux/arm64
